<?php

namespace Database\Seeders;

use App\Models\Blog;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BlogsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Blog::insert([
            [
                'title' => 'Rebuilding Trust in Irish Home Repairs',
                'slug' => Str::slug('Rebuilding Trust Irish Home Repairs'),
                'sub_description' => 'JavaScript frameworks such as React, Angular, and Vue.js have revolutionized the way developers build dynamic user interfaces, making web applications faster and more efficient.',
                'description' => '<p><strong>Ireland’s Housing Goals Are at Risk — Here’s Why</strong></p><p>Ireland has set bold housing and infrastructure targets, including 50,000+ new homes annually by 2030. But a growing shortage of skilled construction labour threatens these ambitions. Over 73% of construction firms say access to skilled workers is their biggest challenge — making it harder to deliver homes, retrofits, and public projects.</p><p><strong>Demand Is Rising, But Labour Isn’t</strong></p><p>In 2024, just 30,300 homes were completed — far below what’s needed. Retrofitting and infrastructure projects add pressure. Estimates suggest the industry needs 80,000+ additional workers, pushing workforce targets to Celtic Tiger–era highs.</p><p><strong>The Skills Gap Is Real</strong></p><p>From bricklayers to engineers, companies report widespread hiring struggles. Many firms face delays, rising labour costs, and stalled projects due to talent shortages. 81% of contractors say they’ve had to cancel or postpone jobs.</p><p><strong>Outdated Hiring Slows Progress</strong></p><p>Despite the crisis, 60% of companies aren’t investing in digital tools. Most hiring still depends on word-of-mouth and slow, manual vetting — a bottleneck in a fast-moving market.</p><p>Ireland is racing to meet ambitious housing and infrastructure goals, but a severe shortage of skilled construction labour is threatening progress. With demand for over 50,000 new homes annually by 2030, and national retrofit plans in motion, the pressure on the workforce has never been higher. Yet, 73% of construction firms report hiring as their number-one challenge, and many are already delaying or cancelling projects due to a lack of qualified workers. The skills gap spans every trade — from bricklayers to engineers — and is worsened by outdated hiring practices that rely heavily on word-of-mouth and paper CVs. As labour costs rise and time-to-hire drags, the need for modern, tech-enabled solutions has become urgent. Platforms like Nixerly are stepping in to close that gap, helping companies find Garda-vetted professionals faster, verify skills efficiently, and keep critical projects on track. To meet Ireland’s housing and climate targets, the industry must embrace digital recruitment, scale workforce development, and adapt to a new era of smarter, faster hiring.</p>',
                'image' => 'backend/images/a4cedc17718403181a07e54ec076a2f57d1c4a7e.jpg',
                'user_id' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Crafted for the Hands That Build Ireland',
                'slug' => Str::slug('Crafted for the Hands Build Ireland'),
                'sub_description' => 'JavaScript frameworks such as React, Angular, and Vue.js have revolutionized the way developers build dynamic user interfaces, making web applications faster and more efficient.',
                'description' => '<p><strong>Ireland’s Housing Goals Are at Risk — Here’s Why</strong></p><p>Ireland has set bold housing and infrastructure targets, including 50,000+ new homes annually by 2030. But a growing shortage of skilled construction labour threatens these ambitions. Over 73% of construction firms say access to skilled workers is their biggest challenge — making it harder to deliver homes, retrofits, and public projects.</p><p><strong>Demand Is Rising, But Labour Isn’t</strong></p><p>In 2024, just 30,300 homes were completed — far below what’s needed. Retrofitting and infrastructure projects add pressure. Estimates suggest the industry needs 80,000+ additional workers, pushing workforce targets to Celtic Tiger–era highs.</p><p><strong>The Skills Gap Is Real</strong></p><p>From bricklayers to engineers, companies report widespread hiring struggles. Many firms face delays, rising labour costs, and stalled projects due to talent shortages. 81% of contractors say they’ve had to cancel or postpone jobs.</p><p><strong>Outdated Hiring Slows Progress</strong></p><p>Despite the crisis, 60% of companies aren’t investing in digital tools. Most hiring still depends on word-of-mouth and slow, manual vetting — a bottleneck in a fast-moving market.</p><p>Ireland is racing to meet ambitious housing and infrastructure goals, but a severe shortage of skilled construction labour is threatening progress. With demand for over 50,000 new homes annually by 2030, and national retrofit plans in motion, the pressure on the workforce has never been higher. Yet, 73% of construction firms report hiring as their number-one challenge, and many are already delaying or cancelling projects due to a lack of qualified workers. The skills gap spans every trade — from bricklayers to engineers — and is worsened by outdated hiring practices that rely heavily on word-of-mouth and paper CVs. As labour costs rise and time-to-hire drags, the need for modern, tech-enabled solutions has become urgent. Platforms like Nixerly are stepping in to close that gap, helping companies find Garda-vetted professionals faster, verify skills efficiently, and keep critical projects on track. To meet Ireland’s housing and climate targets, the industry must embrace digital recruitment, scale workforce development, and adapt to a new era of smarter, faster hiring.</p>',
                'image' => 'backend/images/99a70b0bdd0fa5ed0276159926df9d1c7d505199.jpg',
                'user_id' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Rebuilding Trust in Irish Home Repairs',
                'slug' => Str::slug('Rebuilding Trust in Home Repairs'),
                'sub_description' => 'JavaScript frameworks such as React, Angular, and Vue.js have revolutionized the way developers build dynamic user interfaces, making web applications faster and more efficient.',
                'description' => '<p><strong>Ireland’s Housing Goals Are at Risk — Here’s Why</strong></p><p>Ireland has set bold housing and infrastructure targets, including 50,000+ new homes annually by 2030. But a growing shortage of skilled construction labour threatens these ambitions. Over 73% of construction firms say access to skilled workers is their biggest challenge — making it harder to deliver homes, retrofits, and public projects.</p><p><strong>Demand Is Rising, But Labour Isn’t</strong></p><p>In 2024, just 30,300 homes were completed — far below what’s needed. Retrofitting and infrastructure projects add pressure. Estimates suggest the industry needs 80,000+ additional workers, pushing workforce targets to Celtic Tiger–era highs.</p><p><strong>The Skills Gap Is Real</strong></p><p>From bricklayers to engineers, companies report widespread hiring struggles. Many firms face delays, rising labour costs, and stalled projects due to talent shortages. 81% of contractors say they’ve had to cancel or postpone jobs.</p><p><strong>Outdated Hiring Slows Progress</strong></p><p>Despite the crisis, 60% of companies aren’t investing in digital tools. Most hiring still depends on word-of-mouth and slow, manual vetting — a bottleneck in a fast-moving market.</p><p>Ireland is racing to meet ambitious housing and infrastructure goals, but a severe shortage of skilled construction labour is threatening progress. With demand for over 50,000 new homes annually by 2030, and national retrofit plans in motion, the pressure on the workforce has never been higher. Yet, 73% of construction firms report hiring as their number-one challenge, and many are already delaying or cancelling projects due to a lack of qualified workers. The skills gap spans every trade — from bricklayers to engineers — and is worsened by outdated hiring practices that rely heavily on word-of-mouth and paper CVs. As labour costs rise and time-to-hire drags, the need for modern, tech-enabled solutions has become urgent. Platforms like Nixerly are stepping in to close that gap, helping companies find Garda-vetted professionals faster, verify skills efficiently, and keep critical projects on track. To meet Ireland’s housing and climate targets, the industry must embrace digital recruitment, scale workforce development, and adapt to a new era of smarter, faster hiring.</p>',
                'image' => 'backend/images/de31d9a22fddc22578a51900b9ad0d5d62904523.jpg',
                'user_id' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Crafted for the Hands That Build Ireland',
                'slug' => Str::slug('Crafted for the Hands That Build'),
                'sub_description' => 'JavaScript frameworks such as React, Angular, and Vue.js have revolutionized the way developers build dynamic user interfaces, making web applications faster and more efficient.',
                'description' => '<p><strong>Ireland’s Housing Goals Are at Risk — Here’s Why</strong></p><p>Ireland has set bold housing and infrastructure targets, including 50,000+ new homes annually by 2030. But a growing shortage of skilled construction labour threatens these ambitions. Over 73% of construction firms say access to skilled workers is their biggest challenge — making it harder to deliver homes, retrofits, and public projects.</p><p><strong>Demand Is Rising, But Labour Isn’t</strong></p><p>In 2024, just 30,300 homes were completed — far below what’s needed. Retrofitting and infrastructure projects add pressure. Estimates suggest the industry needs 80,000+ additional workers, pushing workforce targets to Celtic Tiger–era highs.</p><p><strong>The Skills Gap Is Real</strong></p><p>From bricklayers to engineers, companies report widespread hiring struggles. Many firms face delays, rising labour costs, and stalled projects due to talent shortages. 81% of contractors say they’ve had to cancel or postpone jobs.</p><p><strong>Outdated Hiring Slows Progress</strong></p><p>Despite the crisis, 60% of companies aren’t investing in digital tools. Most hiring still depends on word-of-mouth and slow, manual vetting — a bottleneck in a fast-moving market.</p><p>Ireland is racing to meet ambitious housing and infrastructure goals, but a severe shortage of skilled construction labour is threatening progress. With demand for over 50,000 new homes annually by 2030, and national retrofit plans in motion, the pressure on the workforce has never been higher. Yet, 73% of construction firms report hiring as their number-one challenge, and many are already delaying or cancelling projects due to a lack of qualified workers. The skills gap spans every trade — from bricklayers to engineers — and is worsened by outdated hiring practices that rely heavily on word-of-mouth and paper CVs. As labour costs rise and time-to-hire drags, the need for modern, tech-enabled solutions has become urgent. Platforms like Nixerly are stepping in to close that gap, helping companies find Garda-vetted professionals faster, verify skills efficiently, and keep critical projects on track. To meet Ireland’s housing and climate targets, the industry must embrace digital recruitment, scale workforce development, and adapt to a new era of smarter, faster hiring.</p>',
                'image' => 'backend/images/52831f1f16b0205791cc4172c9e6989ac761aeb4.jpg',
                'user_id' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Rebuilding Trust in Irish Home Repairs',
                'slug' => Str::slug('Rebuilding Trust in Irish Home'),
                'sub_description' => 'JavaScript frameworks such as React, Angular, and Vue.js have revolutionized the way developers build dynamic user interfaces, making web applications faster and more efficient.',
                'description' => '<p><strong>Ireland’s Housing Goals Are at Risk — Here’s Why</strong></p><p>Ireland has set bold housing and infrastructure targets, including 50,000+ new homes annually by 2030. But a growing shortage of skilled construction labour threatens these ambitions. Over 73% of construction firms say access to skilled workers is their biggest challenge — making it harder to deliver homes, retrofits, and public projects.</p><p><strong>Demand Is Rising, But Labour Isn’t</strong></p><p>In 2024, just 30,300 homes were completed — far below what’s needed. Retrofitting and infrastructure projects add pressure. Estimates suggest the industry needs 80,000+ additional workers, pushing workforce targets to Celtic Tiger–era highs.</p><p><strong>The Skills Gap Is Real</strong></p><p>From bricklayers to engineers, companies report widespread hiring struggles. Many firms face delays, rising labour costs, and stalled projects due to talent shortages. 81% of contractors say they’ve had to cancel or postpone jobs.</p><p><strong>Outdated Hiring Slows Progress</strong></p><p>Despite the crisis, 60% of companies aren’t investing in digital tools. Most hiring still depends on word-of-mouth and slow, manual vetting — a bottleneck in a fast-moving market.</p><p>Ireland is racing to meet ambitious housing and infrastructure goals, but a severe shortage of skilled construction labour is threatening progress. With demand for over 50,000 new homes annually by 2030, and national retrofit plans in motion, the pressure on the workforce has never been higher. Yet, 73% of construction firms report hiring as their number-one challenge, and many are already delaying or cancelling projects due to a lack of qualified workers. The skills gap spans every trade — from bricklayers to engineers — and is worsened by outdated hiring practices that rely heavily on word-of-mouth and paper CVs. As labour costs rise and time-to-hire drags, the need for modern, tech-enabled solutions has become urgent. Platforms like Nixerly are stepping in to close that gap, helping companies find Garda-vetted professionals faster, verify skills efficiently, and keep critical projects on track. To meet Ireland’s housing and climate targets, the industry must embrace digital recruitment, scale workforce development, and adapt to a new era of smarter, faster hiring.</p>',
                'image' => 'backend/images/de31d9a22fddc22578a51900b9ad0d5d62904523.jpg',
                'user_id' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Crafted for the Hands That Build Ireland',
                'slug' => Str::slug('Crafted for the Hands That Build'),
                'sub_description' => 'JavaScript frameworks such as React, Angular, and Vue.js have revolutionized the way developers build dynamic user interfaces, making web applications faster and more efficient.',
                'description' => '<p><strong>Ireland’s Housing Goals Are at Risk — Here’s Why</strong></p><p>Ireland has set bold housing and infrastructure targets, including 50,000+ new homes annually by 2030. But a growing shortage of skilled construction labour threatens these ambitions. Over 73% of construction firms say access to skilled workers is their biggest challenge — making it harder to deliver homes, retrofits, and public projects.</p><p><strong>Demand Is Rising, But Labour Isn’t</strong></p><p>In 2024, just 30,300 homes were completed — far below what’s needed. Retrofitting and infrastructure projects add pressure. Estimates suggest the industry needs 80,000+ additional workers, pushing workforce targets to Celtic Tiger–era highs.</p><p><strong>The Skills Gap Is Real</strong></p><p>From bricklayers to engineers, companies report widespread hiring struggles. Many firms face delays, rising labour costs, and stalled projects due to talent shortages. 81% of contractors say they’ve had to cancel or postpone jobs.</p><p><strong>Outdated Hiring Slows Progress</strong></p><p>Despite the crisis, 60% of companies aren’t investing in digital tools. Most hiring still depends on word-of-mouth and slow, manual vetting — a bottleneck in a fast-moving market.</p><p>Ireland is racing to meet ambitious housing and infrastructure goals, but a severe shortage of skilled construction labour is threatening progress. With demand for over 50,000 new homes annually by 2030, and national retrofit plans in motion, the pressure on the workforce has never been higher. Yet, 73% of construction firms report hiring as their number-one challenge, and many are already delaying or cancelling projects due to a lack of qualified workers. The skills gap spans every trade — from bricklayers to engineers — and is worsened by outdated hiring practices that rely heavily on word-of-mouth and paper CVs. As labour costs rise and time-to-hire drags, the need for modern, tech-enabled solutions has become urgent. Platforms like Nixerly are stepping in to close that gap, helping companies find Garda-vetted professionals faster, verify skills efficiently, and keep critical projects on track. To meet Ireland’s housing and climate targets, the industry must embrace digital recruitment, scale workforce development, and adapt to a new era of smarter, faster hiring.</p>',
                'image' => 'backend/images/52831f1f16b0205791cc4172c9e6989ac761aeb4.jpg',
                'user_id' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
